spring:
  application:
    name: service-hystrix

server:
  port: 6704

cloud:
  application:
    name: weather-services

eureka:
  client:
    service-url.defaultZone: http://localhost:6501/eureka
   #,localhost:8002/eureka ,http://localhost:6502/eureka

feign:
  hystrix:
    enabled: true

weather-services:
  ribbon:
    eureka:
      enabled: true
    #listOfServers: http://localhost:6501/eureka,http://localhost:6502/eureka
    ServerListRefreshInterval: 15000
